--- #YAML:1.0
name:               Acme-POE-Tree
version:            1.020
abstract:           Merry Christmas from the POE Team
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Curses:   1.15
    IO::Tty:  1.07
    POE:      1.007
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://thirdlobe.com/svn/acme-poe-tree/trunk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
